#ifndef __PYST_PARAM_HPP__
#define __PYST_PARAM_HPP__

#define MAX_PACKET_TOTAL_BYTES_LIMIT 8192
#define N_ID_BYTES 4
#define N_TYPE_BYTES 4
#define N_PORT_BYTES 4
#define N_USER_BYTES 4
#define N_NBR_FIELD_BYTES 1
#define N_EACH_NBR_FIELD_BYTES 2
#define FIELD_BYTE_DEFAULT_VALUE 255

#define ID_BYTE_POS	(N_ID_BYTES - 1) // 4 - 1
#define TYPE_BYTE_POS (ID_BYTE_POS + N_TYPE_BYTES) // 3 + 4
#define PORT_BYTE_POS (TYPE_BYTE_POS + N_PORT_BYTES) // 7 + 4
#define USER_BYTE_POS (PORT_BYTE_POS + N_USER_BYTES) // 11 + 4
#define N_NBR_FIELD_BYTE_POS (USER_BYTE_POS + N_NBR_FIELD_BYTES) // 15 + 1

#endif //

